"""Allow optional bilingual content

Revision ID: 23cac6e59524
Revises: bcbda2bd7c6f
Create Date: 2026-09-19 12:50:41.359998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cac6e59524'
down_revision: Union[str, Sequence[str], None] = 'bcbda2bd7c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('books', 'title_ml',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('building_updates', 'title_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('building_updates', 'title_ml',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('notices', 'title_en',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('notices', 'title_ml',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notices', 'title_ml',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('notices', 'title_en',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('building_updates', 'title_ml',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('building_updates', 'title_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('books', 'title_ml',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('books', 'title_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
