"""Create initial database tables

Revision ID: bcbda2bd7c6f
Revises: 
Create Date: 2026-09-19 11:49:26.491752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbda2bd7c6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('title_ml', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ml', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('title_ml', sa.String(length=300), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ml', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_en', sa.String(length=200), nullable=False),
    sa.Column('label_ml', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=False),
    sa.Column('title_ml', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_en', sa.Text(), nullable=True),
    sa.Column('value_ml', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('title_ml', sa.String(length=300), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ml', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sports')
    op.drop_table('site_settings')
    op.drop_table('notices')
    op.drop_table('library_stats')
    op.drop_table('images')
    op.drop_table('building_updates')
    op.drop_table('books')
    op.drop_table('admins')
    # ### end Alembic commands ###
